ENTITY SubSys_Controller_tb IS
   GENERIC( 
      Burst_length : integer := 8;
      CAS_Latency  : integer := 3;
      CLK_Freq_MHz : integer := 160
   );
-- Declarations

END SubSys_Controller_tb ;

--
-- VHDL Architecture Controller_of_engine_lib.SubSys_Controller_tb.struct
--
-- Created:
--          by - Valera.UNKNOWN (DESKTOP-0191TV9)
--          at - 15:34:31 18.12.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
USE ieee.math_real.ALL;
LIBRARY work;
USE work.SDRAM_controller_Package.ALL;


ARCHITECTURE struct OF SubSys_Controller_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A           : std_logic_vector(11 DOWNTO 0);
   SIGNAL A_FSM       : std_logic_vector(11 DOWNTO 0);
   SIGNAL A_SDRAM     : std_logic_vector(11 DOWNTO 0);
   SIGNAL A_Subsys    : std_logic_vector(11 DOWNTO 0);
   SIGNAL BS          : std_logic_vector(1 DOWNTO 0);
   SIGNAL BS_FSM      : std_logic_vector(1 DOWNTO 0);
   SIGNAL BS_SDRAM    : std_logic_vector(1 DOWNTO 0);
   SIGNAL BS_Subsys   : std_logic_vector(1 DOWNTO 0);
   SIGNAL CKE         : std_logic;
   SIGNAL CKE_FSM     : std_logic;
   SIGNAL CKE_SDRAM   : std_logic;
   SIGNAL CKE_Subsys  : std_logic;
   SIGNAL CLK         : std_logic;
   SIGNAL DQM         : std_logic_vector(1 DOWNTO 0);
   SIGNAL DQM_FSM     : std_logic_vector(1 DOWNTO 0);
   SIGNAL DQM_SDRAM   : std_logic_vector(1 DOWNTO 0);
   SIGNAL DQM_Subsys  : std_logic_vector(1 DOWNTO 0);
   SIGNAL Dq          : std_logic_vector(15 DOWNTO 0);
   SIGNAL StateFSM    : StateFSM_type;
   SIGNAL State_out   : StateSubsys_type;
   SIGNAL nCAS        : std_logic;
   SIGNAL nCAS_FSM    : std_logic;
   SIGNAL nCAS_SDRAM  : std_logic;
   SIGNAL nCAS_Subsys : std_logic;
   --  Выходы на SDRAM
   SIGNAL nCS         : std_logic;
   SIGNAL nCS_FSM     : std_logic;
   SIGNAL nCS_SDRAM   : std_logic;
   -- Выходы на арбитр
   SIGNAL nCS_Subsys  : std_logic;
   SIGNAL nRAS        : std_logic;
   SIGNAL nRAS_FSM    : std_logic;
   SIGNAL nRAS_SDRAM  : std_logic;
   SIGNAL nRAS_Subsys : std_logic;
   -- Общие
   SIGNAL nRst        : std_logic;
   SIGNAL nWE         : std_logic;
   SIGNAL nWE_FSM     : std_logic;
   SIGNAL nWE_SDRAM   : std_logic;
   SIGNAL nWE_Subsys  : std_logic;


   -- Component Declarations
   COMPONENT Controller_SDRAM_arbiter
   PORT (
      -- Общие
      nRst        : IN     std_logic ;
      CLK         : IN     std_logic ;
      -- От FSM
      StateFSM    : IN     StateFSM_type ;
      nCS_FSM     : IN     std_logic ;
      nRAS_FSM    : IN     std_logic ;
      nCAS_FSM    : IN     std_logic ;
      nWE_FSM     : IN     std_logic ;
      CKE_FSM     : IN     std_logic ;
      DQM_FSM     : IN     std_logic_vector (1 DOWNTO 0);
      BS_FSM      : IN     std_logic_vector (1 DOWNTO 0);
      A_FSM       : IN     std_logic_vector (11 DOWNTO 0);
      --  От подсистемы
      nCS_Subsys  : IN     std_logic ;
      nRAS_Subsys : IN     std_logic ;
      nCAS_Subsys : IN     std_logic ;
      nWE_Subsys  : IN     std_logic ;
      CKE_Subsys  : IN     std_logic ;
      DQM_Subsys  : IN     std_logic_vector (1 DOWNTO 0);
      BS_Subsys   : IN     std_logic_vector (1 DOWNTO 0);
      A_Subsys    : IN     std_logic_vector (11 DOWNTO 0);
      --  Выходы на SDRAM
      nCS         : OUT    std_logic ;
      nRAS        : OUT    std_logic ;
      nCAS        : OUT    std_logic ;
      nWE         : OUT    std_logic ;
      CKE         : OUT    std_logic ;
      DQM         : OUT    std_logic_vector (1 DOWNTO 0);
      bs          : OUT    std_logic_vector (1 DOWNTO 0);
      A           : OUT    std_logic_vector (11 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT SubSys_Controller
   GENERIC (
      Burst_length : integer := 8;
      CAS_Latency  : integer := 3;
      CLK_Freq_MHz : integer := 160
   );
   PORT (
      -- Общие
      nRst      : IN     std_logic ;
      CLK       : IN     std_logic ;
      -- Входы с FSM
      StateFSM  : IN     StateFSM_type ;
      A_FSM     : IN     std_logic_vector (11 DOWNTO 0);
      -- Выходы на арбитр
      nCS       : OUT    std_logic ;
      nRAS      : OUT    std_logic ;
      nCAS      : OUT    std_logic ;
      nWE       : OUT    std_logic ;
      CKE       : OUT    std_logic ;
      DQM       : OUT    std_logic_vector (1 DOWNTO 0);
      BS        : OUT    std_logic_vector (1 DOWNTO 0);
      A         : OUT    std_logic_vector (11 DOWNTO 0);
      State_out : OUT    StateSubsys_type 
   );
   END COMPONENT;
   COMPONENT SubSys_Controller_tester
   PORT (
      A         : IN     std_logic_vector (11 DOWNTO 0);
      BS        : IN     std_logic_vector (1 DOWNTO 0);
      CKE       : IN     std_logic ;
      DQM       : IN     std_logic_vector (1 DOWNTO 0);
      Dq        : IN     std_logic_vector (15 DOWNTO 0);
      State_out : IN     StateSubsys_type ;
      nCAS      : IN     std_logic ;
      nCS       : IN     std_logic ;
      nRAS      : IN     std_logic ;
      nWE       : IN     std_logic ;
      A_FSM     : OUT    std_logic_vector (11 DOWNTO 0);
      BS_FSM    : OUT    std_logic_vector (1 DOWNTO 0);
      CKE_FSM   : OUT    std_logic ;
      CLK       : OUT    std_logic ;
      DQM_FSM   : OUT    std_logic_vector (1 DOWNTO 0);
      StateFSM  : OUT    StateFSM_type ;
      nCAS_FSM  : OUT    std_logic ;
      nCS_FSM   : OUT    std_logic ;
      nRAS_FSM  : OUT    std_logic ;
      nRst      : OUT    std_logic ;
      nWE_FSM   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT mt48lc4m16a2
   GENERIC (
      -- // synopsys template
      addr_bits : integer := 12;
      data_bits : integer := 16;
      col_bits  : integer := 8;
      mem_sizes : integer := 1048575
   );
   PORT (
      Dq    : INOUT  std_logic_vector (data_bits - 1 DOWNTO 0);
      Addr  : IN     std_logic_vector (addr_bits - 1 DOWNTO 0);
      Ba    : IN     std_logic_vector (1 DOWNTO 0);
      Clk   : IN     std_logic ;
      Cke   : IN     std_logic ;
      Cs_n  : IN     std_logic ;
      Ras_n : IN     std_logic ;
      Cas_n : IN     std_logic ;
      We_n  : IN     std_logic ;
      Dqm   : IN     std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Controller_SDRAM_arbiter USE ENTITY work.Controller_SDRAM_arbiter;
   FOR ALL : SubSys_Controller USE ENTITY work.SubSys_Controller;
   FOR ALL : SubSys_Controller_tester USE ENTITY work.SubSys_Controller_tester;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   nCS_SDRAM <= nCS after 1.2 ns;
   nRAS_SDRAM <= nRAS after 1.2 ns;
   nCAS_SDRAM <= nCAS after 1.2 ns;
   nWE_SDRAM <= nWE after 1.2 ns;
   CKE_SDRAM <= CKE after 1.2 ns;
   DQM_SDRAM <= DQM after 1.2 ns;
   BS_SDRAM <= BS after 1.2 ns;
   A_SDRAM <= A after 1.2 ns;


   -- Instance port mappings.
   U_2 : Controller_SDRAM_arbiter
      PORT MAP (
         nRst        => nRst,
         CLK         => CLK,
         StateFSM    => StateFSM,
         nCS_FSM     => nCS_FSM,
         nRAS_FSM    => nRAS_FSM,
         nCAS_FSM    => nCAS_FSM,
         nWE_FSM     => nWE_FSM,
         CKE_FSM     => CKE_FSM,
         DQM_FSM     => DQM_FSM,
         BS_FSM      => BS_FSM,
         A_FSM       => A_FSM,
         nCS_Subsys  => nCS_Subsys,
         nRAS_Subsys => nRAS_Subsys,
         nCAS_Subsys => nCAS_Subsys,
         nWE_Subsys  => nWE_Subsys,
         CKE_Subsys  => CKE_Subsys,
         DQM_Subsys  => DQM_Subsys,
         BS_Subsys   => BS_Subsys,
         A_Subsys    => A_Subsys,
         nCS         => nCS,
         nRAS        => nRAS,
         nCAS        => nCAS,
         nWE         => nWE,
         CKE         => CKE,
         DQM         => DQM,
         bs          => BS,
         A           => A
      );
   U_0 : SubSys_Controller
      GENERIC MAP (
         Burst_length => 8,
         CAS_Latency  => 3,
         CLK_Freq_MHz => 160
      )
      PORT MAP (
         nRst      => nRst,
         CLK       => CLK,
         StateFSM  => StateFSM,
         A_FSM     => A_FSM,
         nCS       => nCS_Subsys,
         nRAS      => nRAS_Subsys,
         nCAS      => nCAS_Subsys,
         nWE       => nWE_Subsys,
         CKE       => CKE_Subsys,
         DQM       => DQM_Subsys,
         bs        => BS_Subsys,
         A         => A_Subsys,
         State_out => State_out
      );
   U_1 : SubSys_Controller_tester
      PORT MAP (
         A         => A,
         BS        => BS,
         CKE       => CKE,
         DQM       => DQM,
         Dq        => Dq,
         State_out => State_out,
         nCAS      => nCAS,
         nCS       => nCS,
         nRAS      => nRAS,
         nWE       => nWE,
         A_FSM     => A_FSM,
         BS_FSM    => BS_FSM,
         CKE_FSM   => CKE_FSM,
         CLK       => CLK,
         DQM_FSM   => DQM_FSM,
         StateFSM  => StateFSM,
         nCAS_FSM  => nCAS_FSM,
         nCS_FSM   => nCS_FSM,
         nRAS_FSM  => nRAS_FSM,
         nRst      => nRst,
         nWE_FSM   => nWE_FSM
      );
   U_3 : mt48lc4m16a2
      PORT MAP (
         Dq    => Dq,
         Addr  => A_SDRAM,
         Ba    => BS_SDRAM,
         Clk   => CLK,
         Cke   => CKE_SDRAM,
         Cs_n  => nCS_SDRAM,
         Ras_n => nRAS_SDRAM,
         Cas_n => nCAS_SDRAM,
         We_n  => nWE_SDRAM,
         Dqm   => DQM_SDRAM
      );

END struct;
