LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
USE ieee.math_real.ALL;
LIBRARY work;
USE work.SDRAM_controller_Package.ALL;

ENTITY SubSys_Controller_tester IS
   PORT( 
      A         : IN     std_logic_vector (11 DOWNTO 0);
      BS        : IN     std_logic_vector (1 DOWNTO 0);
      CKE       : IN     std_logic;
      DQM       : IN     std_logic_vector (1 DOWNTO 0);
      Dq        : IN     std_logic_vector (15 DOWNTO 0);
      State_out : IN     StateSubsys_type;
      nCAS      : IN     std_logic;
      --  Выходы на SDRAM
      nCS       : IN     std_logic;
      nRAS      : IN     std_logic;
      nWE       : IN     std_logic;
      A_FSM     : OUT    std_logic_vector (11 DOWNTO 0);
      BS_FSM    : OUT    std_logic_vector (1 DOWNTO 0);
      CKE_FSM   : OUT    std_logic;
      CLK       : OUT    std_logic;
      DQM_FSM   : OUT    std_logic_vector (1 DOWNTO 0);
      StateFSM  : OUT    StateFSM_type;
      nCAS_FSM  : OUT    std_logic;
      nCS_FSM   : OUT    std_logic;
      nRAS_FSM  : OUT    std_logic;
      -- Общие
      nRst      : OUT    std_logic;
      nWE_FSM   : OUT    std_logic
   );

-- Declarations

END SubSys_Controller_tester ;

--
-- VHDL Architecture Controller_of_engine_lib.SubSys_Controller_tester.flow
--
-- Created:
--          by - Valera.UNKNOWN (DESKTOP-0191TV9)
--          at - 23:59:54 14.12.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
USE ieee.math_real.ALL;
LIBRARY work;
USE work.SDRAM_controller_Package.ALL;
ARCHITECTURE flow OF SubSys_Controller_tester IS

   -- Architecture declarations
   signal int_clk : std_logic := '0';
   CONSTANT CLK_PRD: time := 6.25 ns;
   --
   PROCEDURE wait_clock(CONSTANT clk_ticks : integer) IS
   BEGIN
     FOR i in 0 to clk_ticks LOOP
       wait until(rising_edge(CLK));
       wait for 300 ps;
     END LOOP;
   END wait_clock;

BEGIN

   -----------------------------------------------------------------
   main_proc_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      nRst <= '0';
      wait_clock(3);
      nRst <= '1';
      wait;
   END PROCESS main_proc_proc;

   -----------------------------------------------------------------
   fsm_model_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      nCS_FSM <= '1';
      nRAS_FSM <= '1';
      nCAS_FSM <= '1';
      nWE_FSM <= '1';
      A_FSM <= (others => '0');
      BS_FSM <= (others => '0');
      DQM_FSM <= "00";
      CKE_FSM <= '1';
      StateFSM <= Waiting;
      wait until State_out = ValidOp;      
      wait for 5 us;
      StateFSM <= Reading;
      nCS_FSM <= '0';
      nRAS_FSM <= '0';
      nCAS_FSM <= '1';
      nWE_FSM <= '1';
      wait_clock(0);
      nCS_FSM <= '1';
      nRAS_FSM <= '1';
      nCAS_FSM <= '1';
      nWE_FSM <= '1';
      wait_clock(9);
      StateFSM <= Waiting;
      wait until State_out = ValidOp;      
      wait for 5 us;
      StateFSM <= Writing;
      wait_clock(0);
      A_FSM(10) <= '1';
      wait_clock(0);
      A_FSM(10) <= '0';
      wait_clock(8);
      StateFSM <= Waiting;
      wait_clock(30);
      StateFSM <= Reading;
      wait until State_out /= ValidOp;
      wait_clock(4);
      StateFSM <= Waiting;
      wait;
   END PROCESS fsm_model_proc;


-- Architecture concurrent statements
int_clk <= not int_clk AFTER CLK_PRD / 2;
CLK <= int_clk;

END flow;
